#application name
spring.application.name=LabReserve
server.port=8080
#MongoDB configuration
mongodb+srv://admin:admin@classroomdatabase.ddlng.mongodb.net/LabReserve?retryWrites=true&w=majority&appName=ClassRoomDatabase
spring.data.mongodb.uri=mongodb+srv://admin:admin@classroomdatabase.ddlng.mongodb.net/LabReserve?retryWrites=true&w=majority&appName=ClassRoomDatabaseauthMechanism=SCRAM-SHA-1
spring.data.mongodb.database=LabReserve

# Configuracion de logs
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.web=DEBUG

# configuration PKCS12
server.ssl.enabled=true
server.ssl.key-store=classpath:ssl/baeldung.p12
server.ssl.key-store-password=admin1
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=baeldung
# trust store
trust.store=classpath:ssl/baeldung.p12
trust.store.password=admin1
